# Generated by Django 5.0.2 on 2024-02-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_rename_origination_person_origination_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="vehicle_model",
            field=models.CharField(default=str, max_length=64),
            preserve_default=False,
        ),
    ]
