# Generated by Django 5.0.2 on 2024-02-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0005_person_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
    ]
